In [ ]:
import pandas as pd
x = pd.Series([10,20,30], index=['a','b','c'])
print(x)

a    10
b    20
c    30
dtype: int64

In [ ]:
df = pd.DataFrame({
    'name':['Alice','Bob'],
    'age':[25,56]
     })
print(df)

    name  age
0  Alice   25
1    Bob   56

In [ ]:
df=pd.DataFrame([{'a':1,'b':2},{'a':3,'b':4}])
print(df)

   a  b
0  1  2
1  3  4

In [ ]:
df=pd.DataFrame({'A':[1,2,3],'B':['x','y','z']})
print(df)

   A  B
0  1  x
1  2  y
2  3  z

In [ ]:
import numpy as np
a = np.random.randn(100,2)
df= pd.DataFrame(a,columns=['col1','col2'])
print(df)

        col1      col2
0  -0.658209  0.850614
1  -0.111720  0.943517
2   0.282826  0.867568
3   0.867975 -0.888804
4  -1.163319 -0.361273
..       ...       ...
95 -0.295635 -1.385231
96  0.902283  1.541186
97  0.507536  0.396602
98 -1.072020  0.497242
99  0.791317 -0.152688

[100 rows x 2 columns]

In [ ]:
import pandas as pd
df= pd.read_csv('/content/customers-100.csv')
print(df)

    Index      Customer Id First Name Last Name  \
0       1  DD37Cf93aecA6Dc     Sheryl    Baxter
1       2  1Ef7b82A4CAAD10    Preston    Lozano
2       3  6F94879bDAfE5a6        Roy     Berry
3       4  5Cef8BFA16c5e3c      Linda     Olsen
4       5  053d585Ab6b3159     Joanna    Bender
..    ...              ...        ...       ...
95     96  cb8E23e48d22Eae       Karl     Greer
96     97  CeD220bdAaCfaDf       Lynn  Atkinson
97     98  28CDbC0dFe4b1Db       Fred    Guerra
98     99  c23d1D9EE8DEB0A     Yvonne    Farmer
99    100  2354a0E336A91A1   Clarence    Haynes

                            Company               City  \
0                   Rasmussen Group       East Leonard
1                       Vega-Gentry  East Jimmychester
2                     Murillo-Perry      Isabelborough
3   Dominguez, Mcmillan and Donovan         Bensonview
4          Martin, Lang and Andrade     West Priscilla
..                              ...                ...
95                        Carey LLC       East Richard
96            Ware, Burns and Oneal       New Bradview
97                    Schmitt-Jones         Ortegaland
98               Fitzgerald-Harrell    Lake Elijahview
99               Le, Nash and Cross          Judymouth

                       Country                 Phone 1  \
0                        Chile            229.077.5154
1                     Djibouti              5153435776
2          Antigua and Barbuda         +1-539-402-0259
3           Dominican Republic  001-808-617-6467x12895
4   Slovakia (Slovak Republic)  001-234-203-0635x76146
..                         ...                     ...
95                      Guyana     (188)169-1674x58692
96                   Sri Lanka         +1-846-706-2218
97             Solomon Islands    +1-753-067-8419x7170
98                       Aruba           (530)311-9786
99                    Honduras           (753)813-6941

                   Phone 2                           Email Subscription Date  \
0         397.884.0519x718        zunigavanessa@smith.info        2020-08-24
1         686-620-1820x944                 vmata@colon.com        2021-04-23
2      (496)978-3969x58947             beckycarr@hogan.com        2020-03-25
3          +1-813-324-8756     stanleyblackwell@benson.org        2020-06-02
4    001-199-446-3860x3486         colinalvarado@miles.net        2021-04-17
..                     ...                             ...               ...
95    001-841-293-3519x614                hhart@jensen.com        2022-01-30
96            605.413.3198               vkemp@ferrell.com        2021-07-10
97   +1-632-666-7507x92121                swagner@kane.org        2021-09-18
98  001-869-452-0943x12424  mccarthystephen@horn-green.biz        2021-08-11
99            783.639.1472          colleen91@faulkner.biz        2020-03-11

                              Website
0          http://www.stephenson.com/
1               http://www.hobbs.com/
2            http://www.lawrence.com/
3          http://www.good-lyons.com/
4         https://goodwin-ingram.com/
..                                ...
95            http://hayes-perez.com/
96         https://novak-allison.com/
97              https://www.ross.com/
98               http://watkins.info/
99  http://www.hatfield-saunders.net/

[100 rows x 12 columns]

In [ ]:
df=pd.read_csv('/content/placement.CSV')
print(df)

     cgpa  package
0    6.89     3.26
1    5.12     1.98
2    7.82     3.25
3    7.42     3.67
4    6.94     3.57
..    ...      ...
196  5.89     2.57
197  7.21     3.24
198  7.63     3.96
199  6.22     2.33
200   NaN      NaN

[201 rows x 2 columns]

In [ ]:
df.head()

   cgpa  package
0  6.89     3.26
1  5.12     1.98
2  7.82     3.25
3  7.42     3.67
4  6.94     3.57

In [ ]:
df.tail()

     cgpa  package
196  5.89     2.57
197  7.21     3.24
198  7.63     3.96
199  6.22     2.33
200   NaN      NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 201 entries, 0 to 200
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   cgpa     200 non-null    float64
 1   package  200 non-null    float64
dtypes: float64(2)
memory usage: 3.3 KB

In [ ]:
df.describe()

             cgpa     package
count  200.000000  200.000000
mean     6.990500    2.996050
std      1.069409    0.691644
min      4.260000    1.370000
25%      6.190000    2.487500
50%      6.965000    2.995000
75%      7.737500    3.492500
max      9.580000    4.620000

In [ ]:
df['cgpa']

0      6.89
1      5.12
2      7.82
3      7.42
4      6.94
       ...
196    5.89
197    7.21
198    7.63
199    6.22
200     NaN
Name: cgpa, Length: 201, dtype: float64

In [ ]:
df.loc[50:78]

    cgpa  package
50  9.58     4.43
51  9.26     3.79
52  8.37     4.11
53  6.47     2.61
54  6.86     3.09
55  8.20     3.39
56  5.84     2.74
57  6.60     1.94
58  6.92     3.09
59  7.56     3.31
60  5.61     2.19
61  5.48     1.61
62  6.34     2.09
63  9.16     4.25
64  7.36     2.92
65  7.60     3.81
66  5.11     1.63
67  6.51     2.89
68  7.56     2.99
69  7.30     2.94
70  5.79     2.35
71  7.47     3.34
72  7.78     3.62
73  8.44     4.03
74  6.85     3.44
75  6.97     3.28
76  6.94     3.15
77  8.99     4.60
78  6.59     2.21

In [ ]:
df.loc[0:100:10]

     cgpa  package
0    6.89     3.26
10   5.32     1.86
20   7.28     3.16
30   7.36     3.26
40   9.38     4.02
50   9.58     4.43
60   5.61     2.19
70   5.79     2.35
80   7.63     3.44
90   7.11     2.66
100  7.95     4.14

In [ ]:
df.dropna()

     cgpa  package
0    6.89     3.26
1    5.12     1.98
2    7.82     3.25
3    7.42     3.67
4    6.94     3.57
..    ...      ...
195  6.93     2.46
196  5.89     2.57
197  7.21     3.24
198  7.63     3.96
199  6.22     2.33

[200 rows x 2 columns]