In [ ]:
import pandas as pd

In [ ]:
df= pd.read_csv('/content/archive.zip')

In [ ]:
print(df)

     Student_ID  Age  Gender Academic_Level     Country  \
0             1   19  Female  Undergraduate  Bangladesh
1             2   22    Male       Graduate       India
2             3   20  Female  Undergraduate         USA
3             4   18    Male    High School          UK
4             5   21    Male       Graduate      Canada
..          ...  ...     ...            ...         ...
700         701   20  Female  Undergraduate       Italy
701         702   23    Male       Graduate      Russia
702         703   21  Female  Undergraduate       China
703         704   24    Male       Graduate       Japan
704         705   19  Female  Undergraduate      Poland

     Avg_Daily_Usage_Hours Most_Used_Platform Affects_Academic_Performance  \
0                      5.2          Instagram                          Yes
1                      2.1            Twitter                           No
2                      6.0             TikTok                          Yes
3                      3.0            YouTube                           No
4                      4.5           Facebook                          Yes
..                     ...                ...                          ...
700                    4.7             TikTok                           No
701                    6.8          Instagram                          Yes
702                    5.6             WeChat                          Yes
703                    4.3            Twitter                           No
704                    6.2           Facebook                          Yes

     Sleep_Hours_Per_Night  Mental_Health_Score Relationship_Status  \
0                      6.5                    6     In Relationship
1                      7.5                    8              Single
2                      5.0                    5         Complicated
3                      7.0                    7              Single
4                      6.0                    6     In Relationship
..                     ...                  ...                 ...
700                    7.2                    7     In Relationship
701                    5.9                    4              Single
702                    6.7                    6     In Relationship
703                    7.5                    8              Single
704                    6.3                    5              Single

     Conflicts_Over_Social_Media  Addicted_Score
0                              3               8
1                              0               3
2                              4               9
3                              1               4
4                              2               7
..                           ...             ...
700                            2               5
701                            5               9
702                            3               7
703                            2               4
704                            4               8

[705 rows x 13 columns]

In [ ]:
df.head()

,Student_ID,Age,Gender,Academic_Level,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Affects_Academic_Performance,Sleep_Hours_Per_Night,Mental_Health_Score,Relationship_Status,Conflicts_Over_Social_Media,Addicted_Score
0,1,19,Female,Undergraduate,Bangladesh,5.2,Instagram,Yes,6.5,6,In Relationship,3,8
1,2,22,Male,Graduate,India,2.1,Twitter,No,7.5,8,Single,0,3
2,3,20,Female,Undergraduate,USA,6.0,TikTok,Yes,5.0,5,Complicated,4,9
3,4,18,Male,High School,UK,3.0,YouTube,No,7.0,7,Single,1,4
4,5,21,Male,Graduate,Canada,4.5,Facebook,Yes,6.0,6,In Relationship,2,7

In [ ]:
df.tail()

,Student_ID,Age,Gender,Academic_Level,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Affects_Academic_Performance,Sleep_Hours_Per_Night,Mental_Health_Score,Relationship_Status,Conflicts_Over_Social_Media,Addicted_Score
700,701,20,Female,Undergraduate,Italy,4.7,TikTok,No,7.2,7,In Relationship,2,5
701,702,23,Male,Graduate,Russia,6.8,Instagram,Yes,5.9,4,Single,5,9
702,703,21,Female,Undergraduate,China,5.6,WeChat,Yes,6.7,6,In Relationship,3,7
703,704,24,Male,Graduate,Japan,4.3,Twitter,No,7.5,8,Single,2,4
704,705,19,Female,Undergraduate,Poland,6.2,Facebook,Yes,6.3,5,Single,4,8

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 705 entries, 0 to 704
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Student_ID                    705 non-null    int64
 1   Age                           705 non-null    int64
 2   Gender                        705 non-null    object
 3   Academic_Level                705 non-null    object
 4   Country                       705 non-null    object
 5   Avg_Daily_Usage_Hours         705 non-null    float64
 6   Most_Used_Platform            705 non-null    object
 7   Affects_Academic_Performance  705 non-null    object
 8   Sleep_Hours_Per_Night         705 non-null    float64
 9   Mental_Health_Score           705 non-null    int64
 10  Relationship_Status           705 non-null    object
 11  Conflicts_Over_Social_Media   705 non-null    int64
 12  Addicted_Score                705 non-null    int64
dtypes: float64(2), int64(5), object(6)
memory usage: 71.7+ KB

In [ ]:
df.describe()

,Student_ID,Age,Avg_Daily_Usage_Hours,Sleep_Hours_Per_Night,Mental_Health_Score,Conflicts_Over_Social_Media,Addicted_Score
count,705.000000,705.000000,705.000000,705.000000,705.000000,705.000000,705.000000
mean,353.000000,20.659574,4.918723,6.868936,6.226950,2.849645,6.436879
std,203.660256,1.399217,1.257395,1.126848,1.105055,0.957968,1.587165
min,1.000000,18.000000,1.500000,3.800000,4.000000,0.000000,2.000000
25%,177.000000,19.000000,4.100000,6.000000,5.000000,2.000000,5.000000
50%,353.000000,21.000000,4.800000,6.900000,6.000000,3.000000,7.000000
75%,529.000000,22.000000,5.800000,7.700000,7.000000,4.000000,8.000000
max,705.000000,24.000000,8.500000,9.600000,9.000000,5.000000,9.000000

In [ ]:
df1=df['Country']
df1

0      Bangladesh
1           India
2             USA
3              UK
4          Canada
          ...
700         Italy
701        Russia
702         China
703         Japan
704        Poland
Name: Country, Length: 705, dtype: object

In [ ]:
df2= df[['Age','Country']]
df2

     Age     Country
0     19  Bangladesh
1     22       India
2     20         USA
3     18          UK
4     21      Canada
..   ...         ...
700   20       Italy
701   23      Russia
702   21       China
703   24       Japan
704   19      Poland

[705 rows x 2 columns]

In [ ]:
df.loc[0]

Student_ID                                    1
Age                                          19
Gender                                   Female
Academic_Level                    Undergraduate
Country                              Bangladesh
Avg_Daily_Usage_Hours                       5.2
Most_Used_Platform                    Instagram
Affects_Academic_Performance                Yes
Sleep_Hours_Per_Night                       6.5
Mental_Health_Score                           6
Relationship_Status             In Relationship
Conflicts_Over_Social_Media                   3
Addicted_Score                                8
Name: 0, dtype: object

In [ ]:
df.iloc[0]

Student_ID                                    1
Age                                          19
Gender                                   Female
Academic_Level                    Undergraduate
Country                              Bangladesh
Avg_Daily_Usage_Hours                       5.2
Most_Used_Platform                    Instagram
Affects_Academic_Performance                Yes
Sleep_Hours_Per_Night                       6.5
Mental_Health_Score                           6
Relationship_Status             In Relationship
Conflicts_Over_Social_Media                   3
Addicted_Score                                8
Name: 0, dtype: object

In [ ]:
df.loc[0:5]

,Student_ID,Age,Gender,Academic_Level,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Affects_Academic_Performance,Sleep_Hours_Per_Night,Mental_Health_Score,Relationship_Status,Conflicts_Over_Social_Media,Addicted_Score
0,1,19,Female,Undergraduate,Bangladesh,5.2,Instagram,Yes,6.5,6,In Relationship,3,8
1,2,22,Male,Graduate,India,2.1,Twitter,No,7.5,8,Single,0,3
2,3,20,Female,Undergraduate,USA,6.0,TikTok,Yes,5.0,5,Complicated,4,9
3,4,18,Male,High School,UK,3.0,YouTube,No,7.0,7,Single,1,4
4,5,21,Male,Graduate,Canada,4.5,Facebook,Yes,6.0,6,In Relationship,2,7
5,6,19,Female,Undergraduate,Australia,7.2,Instagram,Yes,4.5,4,Complicated,5,9

In [ ]:
df.iloc[0:5]

,Student_ID,Age,Gender,Academic_Level,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Affects_Academic_Performance,Sleep_Hours_Per_Night,Mental_Health_Score,Relationship_Status,Conflicts_Over_Social_Media,Addicted_Score
0,1,19,Female,Undergraduate,Bangladesh,5.2,Instagram,Yes,6.5,6,In Relationship,3,8
1,2,22,Male,Graduate,India,2.1,Twitter,No,7.5,8,Single,0,3
2,3,20,Female,Undergraduate,USA,6.0,TikTok,Yes,5.0,5,Complicated,4,9
3,4,18,Male,High School,UK,3.0,YouTube,No,7.0,7,Single,1,4
4,5,21,Male,Graduate,Canada,4.5,Facebook,Yes,6.0,6,In Relationship,2,7

In [ ]:
df.head()

,Student_ID,Age,Gender,Academic_Level,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Affects_Academic_Performance,Sleep_Hours_Per_Night,Mental_Health_Score,Relationship_Status,Conflicts_Over_Social_Media,Addicted_Score
0,1,19,Female,Undergraduate,Bangladesh,5.2,Instagram,Yes,6.5,6,In Relationship,3,8
1,2,22,Male,Graduate,India,2.1,Twitter,No,7.5,8,Single,0,3
2,3,20,Female,Undergraduate,USA,6.0,TikTok,Yes,5.0,5,Complicated,4,9
3,4,18,Male,High School,UK,3.0,YouTube,No,7.0,7,Single,1,4
4,5,21,Male,Graduate,Canada,4.5,Facebook,Yes,6.0,6,In Relationship,2,7

In [ ]:
df3=df[['Age','Gender']]
df3

     Age  Gender
0     19  Female
1     22    Male
2     20  Female
3     18    Male
4     21    Male
..   ...     ...
700   20  Female
701   23    Male
702   21  Female
703   24    Male
704   19  Female

[705 rows x 2 columns]

In [ ]:
df['Age']>22

0      False
1      False
2      False
3      False
4      False
       ...
700    False
701     True
702    False
703     True
704    False
Name: Age, Length: 705, dtype: bool